apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: logstream-*
    isDefault: true
    jsonData:
      timeField: "@timestamp"
      esVersion: 8.11.0
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: log_level
    editable: true